# Generated by Django 3.2.7 on 2021-09-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
        ('course', '0002_course_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessons',
            field=models.ManyToManyField(blank=True, to='lesson.Lesson'),
        ),
    ]
