# Generated by Django 3.2.7 on 2022-04-29 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category',
        ),
        migrations.RemoveField(
            model_name='taskgroup',
            name='author',
        ),
    ]
