# Generated by Django 3.2.7 on 2022-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220429_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='data_close',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='data_open',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='data_part_close',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='local',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='open',
            field=models.BooleanField(default=0),
        ),
    ]
