# Generated by Django 3.2.7 on 2022-04-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20220429_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='data_close',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='data_open',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='taskgroup',
            name='data_part_close',
            field=models.DateTimeField(null=True),
        ),
    ]
