# Generated by Django 3.2.7 on 2022-05-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20220429_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskgroup',
            old_name='data_close',
            new_name='date_close',
        ),
        migrations.RenameField(
            model_name='taskgroup',
            old_name='data_open',
            new_name='date_open',
        ),
        migrations.RenameField(
            model_name='taskgroup',
            old_name='data_part_close',
            new_name='date_part_close',
        ),
    ]
