# Generated by Django 3.2.7 on 2022-05-01 16:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20220501_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='integer_format_flag',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='text_format_flag',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='taskanswers',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskanswers',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
