# Generated by Django 3.2.7 on 2022-05-07 19:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20220501_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
