# Generated by Django 3.2.7 on 2022-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number_of_attempts',
            field=models.IntegerField(default=100),
        ),
    ]
