# Generated by Django 3.2.24 on 2024-02-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20240208_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='files',
        ),
        migrations.AddField(
            model_name='taskanswers',
            name='files',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
        migrations.DeleteModel(
            name='TaskFiles',
        ),
    ]
