# Generated by Django 3.2.24 on 2024-02-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_taskanswers_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswers',
            name='files',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
    ]
