# Generated by Django 3.2.24 on 2024-02-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_taskanswers_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskanswers',
            name='files',
            field=models.FileField(blank=True, upload_to='user_answers'),
        ),
    ]
