# Generated by Django 3.2.7 on 2022-04-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20220429_1801'),
        ('lesson', '0006_alter_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='blocks',
            field=models.ManyToManyField(to='tasks.TaskGroup'),
        ),
    ]
